import React, { useRef } from "react";
import { ActivityIndicator, Animated, Pressable, ScrollView, StyleSheet, Text, TextInput, View, ViewStyle } from "react-native";
import { theme } from "../theme";

export function PressScale({ children, onPress, disabled, style, pressedScale = 0.975 }: { children: React.ReactNode; onPress?: () => void; disabled?: boolean; style?: ViewStyle | ViewStyle[]; pressedScale?: number }) {
  const scale = useRef(new Animated.Value(1)).current;
  const animateTo = (value: number) => Animated.spring(scale, { toValue: value, useNativeDriver: true, speed: 32, bounciness: 3 }).start();
  return <Animated.View style={[{ transform: [{ scale }] }, style]}><Pressable disabled={disabled} onPress={onPress} onPressIn={() => animateTo(pressedScale)} onPressOut={() => animateTo(1)} style={disabled ? { opacity: 0.5 } : undefined}>{children}</Pressable></Animated.View>;
}

export function Page({ children, onBack, title, eyebrow }: { children: React.ReactNode; onBack?: () => void; title?: string; eyebrow?: string }) {
  return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled" contentInsetAdjustmentBehavior="automatic">
    {onBack ? <PressScale onPress={onBack} style={styles.backMotion}><View style={styles.back}><View style={styles.backIconWrap}><Text style={styles.backIcon}>←</Text></View><View><Text style={styles.backText}>Volver al inicio</Text><Text style={styles.backHint}>Regresá a la pantalla principal</Text></View></View></PressScale> : null}
    {eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}
    {title ? <Text style={styles.title}>{title}</Text> : null}
    {children}
  </ScrollView>;
}

export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle | ViewStyle[] }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Field({ label, value, onChangeText, placeholder, multiline }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#70889F" multiline={multiline} style={[styles.input, multiline && styles.multiline]} /></View>; }
export function Chips({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (value: string) => void }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><View style={styles.chips}>{options.map((option) => { const selected = option === value; return <PressScale key={option} onPress={() => onChange(option)}><View style={[styles.chip, selected && styles.chipSelected]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{option}</Text></View></PressScale>; })}</View></View>; }
export function MultiChips({ label, options, values, onChange, helper }: { label: string; options: string[]; values: string[]; onChange: (values: string[]) => void; helper?: string }) { const toggle = (option: string) => onChange(values.includes(option) ? values.filter((v) => v !== option) : [...values, option]); return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text>{helper ? <Text style={styles.helper}>{helper}</Text> : null}<View style={styles.chips}>{options.map((option) => { const selected = values.includes(option); return <PressScale key={option} onPress={() => toggle(option)}><View style={[styles.chip, selected && styles.chipSelected]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{selected ? "✓ " : ""}{option}</Text></View></PressScale>; })}</View></View>; }
export function PrimaryButton({ title, onPress, disabled }: { title: string; onPress: () => void; disabled?: boolean }) { return <PressScale disabled={disabled} onPress={onPress} style={styles.primaryButtonMotion}><View style={styles.primaryButton}><Text style={styles.primaryButtonText}>{title}</Text><Text style={styles.primaryArrow}>→</Text></View></PressScale>; }
export function ResultBox({ loading, error, result }: { loading: boolean; error?: string; result?: string }) { if (loading) return <Card style={styles.successBox}><ActivityIndicator color={theme.colors.gold} /><Text style={styles.loading}>Preparando una respuesta pastoral…</Text></Card>; if (error) return <Card style={styles.errorBox}><Text style={styles.errorEyebrow}>NO SE PUDO COMPLETAR</Text><Text style={styles.error}>{error}</Text></Card>; if (!result) return null; return <Card style={styles.successBox}><Text style={styles.stateEyebrow}>RESPUESTA PREPARADA</Text><Text style={styles.resultTitle}>Guía pastoral</Text><Text style={styles.result}>{result}</Text></Card>; }
export function SectionIntro({ text }: { text: string }) { return <Text style={styles.intro}>{text}</Text>; }

const styles = StyleSheet.create({
  page: { padding: 18, paddingBottom: 44, backgroundColor: theme.colors.background, minHeight: "100%" },
  backMotion: { alignSelf: "flex-start", marginTop: 6, marginBottom: 18 }, back: { flexDirection: "row", alignItems: "center", backgroundColor: theme.colors.surface, borderRadius: 18, borderWidth: 1, borderColor: theme.colors.borderGold, paddingVertical: 10, paddingHorizontal: 12, minHeight: 60 }, backIconWrap: { width: 40, height: 40, borderRadius: 13, backgroundColor: theme.colors.gold, alignItems: "center", justifyContent: "center", marginRight: 10 }, backIcon: { color: theme.colors.navy, fontSize: 22, fontWeight: "900" }, backText: { color: theme.colors.ink, fontSize: 17, fontWeight: "900" }, backHint: { color: theme.colors.muted, fontSize: 13, marginTop: 2 },
  eyebrow: { textTransform: "uppercase", letterSpacing: 1.2, color: theme.colors.goldBright, fontSize: 13, fontWeight: "900", marginBottom: 7 }, title: { color: "#FFFFFF", fontSize: 32, lineHeight: 38, fontWeight: "900", marginBottom: 11 }, intro: { color: "#C8D5E0", fontSize: 17, lineHeight: 26, marginBottom: 20 },
  card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, padding: 18, marginBottom: 14 }, fieldWrap: { marginBottom: 18 }, label: { color: theme.colors.ink, fontSize: 16, fontWeight: "900", marginBottom: 9 }, helper: { color: theme.colors.muted, fontSize: 14, lineHeight: 20, marginBottom: 10 }, input: { minHeight: 54, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, color: theme.colors.ink, backgroundColor: "#071D31", fontSize: 17 }, multiline: { minHeight: 104, textAlignVertical: "top" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 11, backgroundColor: "#0A2035" }, chipSelected: { backgroundColor: theme.colors.gold, borderColor: theme.colors.gold }, chipText: { color: theme.colors.ink, fontSize: 15, fontWeight: "800" }, chipTextSelected: { color: theme.colors.navy },
  primaryButtonMotion: { marginBottom: 14 }, primaryButton: { minHeight: 62, backgroundColor: theme.colors.gold, borderRadius: 18, alignItems: "center", justifyContent: "center", paddingHorizontal: 54 }, primaryButtonText: { color: theme.colors.navy, fontSize: 17, fontWeight: "900" }, primaryArrow: { position: "absolute", right: 20, color: theme.colors.navy, fontSize: 22, fontWeight: "900" },
  successBox: { backgroundColor: "#0B2238", borderColor: "#7A5B24", minHeight: 110 }, errorBox: { backgroundColor: "#2A1820", borderColor: "#6E3940" }, loading: { marginTop: 12, color: "#F7F3EA", fontSize: 14, lineHeight: 21 }, errorEyebrow: { color: theme.colors.danger, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 7 }, error: { color: "#F7F3EA", fontSize: 14, lineHeight: 22 }, stateEyebrow: { color: theme.colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, resultTitle: { color: "#F7F3EA", fontSize: 17, fontWeight: "900", marginTop: 3, marginBottom: 12 }, result: { color: "#F7F3EA", fontSize: 15, lineHeight: 24 }
});
